-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 12:09:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL,
  `Contacto` VARCHAR(45) NULL,
  `Fax` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamentos` (
  `idMedicamentos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Creacion` INT NULL,
  `U_stock` VARCHAR(45) NULL,
  `U_vendidas` VARCHAR(45) NULL,
  `Familia` VARCHAR(45) NULL,
  `Precio` DECIMAL(12,5) NULL,
  `Tipo_venta` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedicamentos`),
  INDEX `fk_lab_idx` (`Creacion` ASC) VISIBLE,
  CONSTRAINT `fk_lab`
    FOREIGN KEY (`Creacion`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_Pago` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Instante_compra` DATETIME NOT NULL,
  `Tipo_usuario` VARCHAR(45) NULL,
  `Precio_Compra` INT NULL,
  PRIMARY KEY (`Instante_compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_Compras` (
  `DNI` INT NOT NULL,
  `Id_cuenta` DATETIME NOT NULL,
  PRIMARY KEY (`DNI`, `Id_cuenta`),
  INDEX `fk_id_compra_idx` (`Id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_dni`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_compra`
    FOREIGN KEY (`Id_cuenta`)
    REFERENCES `mydb`.`Ticket` (`Instante_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrada Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrada Ticket` (
  `Unidades` INT NULL,
  `id_medicamento` INT NOT NULL,
  `id_cuenta` DATETIME NOT NULL,
  `Precio` INT NULL,
  PRIMARY KEY (`id_medicamento`, `id_cuenta`),
  INDEX `fk_id_cuenta_idx` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_medica`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `mydb`.`Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_cuenta`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `mydb`.`Ticket` (`Instante_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
